on:
 push:
  branches:
    -master 



    jobs:
     build:
      runs-on: windows

        steps:
        - name: 'testing github action'
           run: pwd
         - name : 'testing printing'
          run: echo Ramadan

